################################# Default configuration ###################
baseURL = "https://shivangi0304.github.io/vs/"
title = "Vivekananda Samiti IITK"
theme = "airspace-hugo"
publishDir = "docs"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

[[menu.main]]
name = "Activities"
URL = "activities"
weight = 2

[[menu.main]]
name = "Online Resources"
URL = "online-resources"
weight = 3

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[menu.main]]
weight = 5
name = "Events"
hasChildren = true

  [[menu.main]]
  parent = "Events"
  name = "VYLC"
  URL = "vylc"

  #[[menu.main]]
  #parent = "Pages"
  #name = "Discussion Forum"
  #URL = "discussion"
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 6


# footer menu
[[menu.footer]]
name = "About"
URL = "about"
weight = 1

[[menu.footer]]
name = "Activities"
URL = "activities"
weight = 2

[[menu.footer]]
name = "Online Resources"
URL = "online-resources"
weight = 3

[[menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

#[[menu.footer]]
#name = "Discussion"
#URL = "discussion"
#weight = 5

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 5


#################### default parameters ################################
[params]
logo = "images/vslogo.png"
# Meta data
description = "This is meta description"
author = "Vivekananda Samiti IITK"
# Contact Information
phone = "+918920138234"
#mobile = "+918920138234"
email = "vsamiti@gmail.com"
location = "Indian Institute of Technology, Kalyanpur, Kanpur"
# contact form action
contact_form_action = "https://formspree.io/myyndjjn" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

  
############################# social site ########################
#[[params.social]]
#icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/vivekananda-samiti-342902105/?originalSubdomain=in"

#[[params.social]]
#icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/vsiitk"

[[params.social]]
icon = "ion-social-youtube-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.youtube.com/channel/UCfdkUoljOaVEste1ytCWHjg?app=desktop"

[[params.social]]
icon = "ion-social-youtube-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.youtube.com/channel/UCwxGr_R4cbgn7cDBxWPbHfQ"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/vsiitk"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 Vivekananda Samiti, IIT Kanpur All Rights Reserved"

